name: tests-auth

on: 
  push:
  
  pull_request:
    paths:
      - 'src/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - run:  npm install && npm run test:ci
